export const GET_NOVELS_REQUEST='GET_NOVELS_REQUEST'
export const GET_NOVELS_SUCCESS='GET_NOVELS_SUCCESS'
export const GET_NOVELS_FAILURE='GET_NOVELS_FAILURE'

export const ADD_CART_DATA_REQUEST ='ADD_CART_DATA_REQUEST'
export const ADD_CART_DATA_SUCCESS ='ADD_CART_DATA_SUCCESS'
export const ADD_CART_DATA_FAILURE ='ADD_CART_DATA_FAILURE'

export const FETCH_CART_SUCCESS='FETCH_CART_SUCCESS'

export const DELETE_CART_DATA_REUEST='DELETE_CART_DATA_REUEST'
export const DELETE_CART_DATA_SUCCESS='DELETE_CART_DATA_SUCCESS'
export const DELETE_CART_DATA_FAILURE='DELETE_CART_DATA_FAILURE'



export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"